"""create user table

Revision ID: 005ce6e94401
Revises: 
Create Date: 2021-02-16 16:17:14.968184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "005ce6e94401"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("password", sa.Unicode(length=255), nullable=False),
        sa.Column("email", sa.Unicode(length=255), nullable=False),
        sa.Column("nickname", sa.Unicode(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("is_doctor", sa.Boolean()),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("content", sa.Unicode(length=10000)),
        sa.Column("userId", sa.BigInteger, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "doctors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("hospital", sa.Unicode(length=10000)),
        sa.Column("userId", sa.BigInteger, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False)
    )

    op.create_table(
        "answers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("content", sa.Unicode(length=10000)),
        sa.Column("questionId", sa.BigInteger, nullable=False),
        sa.Column("userId", sa.BigInteger, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "boards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.BigInteger, nullable=False),
        sa.Column("categoryId", sa.BigInteger, nullable=False),
        sa.Column("categoryName", sa.Unicode(length=10000)),
        sa.Column("content", sa.Unicode(length=10000)),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("users")
    # op.create_table("questions")
    # ### end Alembic commands ###
